import { Room, BookingAddOn, Attraction, ChannelSyncStatus, Booking } from './types';

export const SUPPORT_PHONE = '(088) 557740';
export const GUEST_HOUSE_ADDRESS = '14 St. Peter\'s Grove, Bootham, York, YO30 6AQ, United Kingdom';
export const GUEST_HOUSE_EMAIL = 'reservations@theyorkguesthouse.co.uk';

export const ROOMS: Room[] = [
  {
    id: 'minster-penthouse',
    name: 'The Minster View Penthouse',
    slug: 'minster-view-penthouse',
    tagline: 'Panoramic gothic views with freestanding copper soaking tub',
    description: 'Perched on the top floor, this romantic sanctuary offers uninterrupted vistas of the majestic York Minster towers. Features exposed vaulted oak trusses, a bespoke super-king Hypnos bed, luxury Belgian linen, and an ensuite with dual basins and a hand-hammered copper bathtub.',
    pricePerNight: 235,
    weekendPrice: 275,
    maxGuests: 2,
    bedType: 'Super King Bed (Zip & Link option)',
    sizeSqM: 42,
    floor: '3rd Floor (Penthouse)',
    view: 'York Minster Cathedral & Historic Rooftops',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'York Minster Cathedral View',
      'Freestanding Copper Bathtub',
      'Hypnos Ortho Luxe Bedding',
      'Dyson Supersonic Hairdryer',
      'Yorkshire Artisan Nespresso & Tea Bar',
      'Smart 55" 4K OLED TV with Netflix',
      'Complimentary Ultra-Fast Fibre Wi-Fi',
      'Organic Bramley Botanical Toiletries',
      'Plush Waffle Robes & Slippers',
      'Silent In-Room Mini Fridge'
    ],
    highlights: [
      'Best view in York',
      'Dual shower & copper tub',
      'Champagne on ice upon arrival'
    ],
    badge: 'Signature Suite',
    totalUnits: 1,
  },
  {
    id: 'shambles-georgian-suite',
    name: 'The Shambles Georgian Suite',
    slug: 'shambles-georgian-suite',
    tagline: 'Timeless 18th-century grandeur with original sash windows',
    description: 'Immerse yourself in authentic Yorkshire heritage. Decorated with William Morris heritage wallpaper, antique mahogany writing desk, high decorative cornices, and an oversized king bed with goose-down topper. The spacious limestone bathroom features an invigorating rainfall walk-in shower.',
    pricePerNight: 195,
    weekendPrice: 225,
    maxGuests: 2,
    bedType: 'King Size Bed',
    sizeSqM: 36,
    floor: '1st Floor',
    view: 'Private Victorian Courtyard & Wisteria Garden',
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Garden Courtyard View',
      'Spacious Rain Walk-in Shower',
      'Antique Georgian Seating Area',
      'Yorkshire Tea & Local Fudge Hamper',
      'Smart 50" 4K TV',
      'Ultra-Fast Wi-Fi',
      'Bramley Botanical Products',
      'Heated Towel Radiators',
      'USB-C Fast Bedside Chargers',
      'Silent Acoustic Secondary Glazing'
    ],
    highlights: [
      'Original 18th-century architecture',
      'Quiet garden courtyard outlook',
      'Luxurious oversized rain shower'
    ],
    badge: 'Guest Favorite',
    totalUnits: 1,
  },
  {
    id: 'eboracum-royal-deluxe',
    name: 'The Eboracum Royal Deluxe',
    slug: 'eboracum-royal-deluxe',
    tagline: 'Deep velvet comfort, marble fireplace & cozy reading nook',
    description: 'Named after Roman York (Eboracum), this grand room combines historic charm with cutting-edge comfort. Features rich midnight blue velvet upholstery, an ornamental Victorian fireplace, custom reading armchairs with reading lamps, and a decadent king bed.',
    pricePerNight: 175,
    weekendPrice: 205,
    maxGuests: 2,
    bedType: 'King Bed or Twin configuration',
    sizeSqM: 34,
    floor: '2nd Floor',
    view: 'Tree-lined Historic St. Peter\'s Grove',
    images: [
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Victorian Feature Fireplace',
      'Luxury En-suite with Walk-in Shower',
      'Twin or King Bed Configuration',
      'Dedicated Reading Armchairs',
      'York Artisan Coffee Pods & Fresh Milk',
      'Smart HD TV',
      'High-Speed Wi-Fi',
      'Organic Bath Products',
      'Ironing Station & Hairdryer',
      'Complimentary Bottled Spring Water'
    ],
    highlights: [
      'Twin or King flexibility',
      'Grand Victorian proportions',
      'Morning sunlight aspect'
    ],
    badge: 'Popular for Couples',
    totalUnits: 1,
  },
  {
    id: 'roman-wall-snug',
    name: 'The Roman Wall Heritage Room',
    slug: 'roman-wall-heritage-room',
    tagline: 'Intimate, warm & whisper-quiet sanctuary for restful sleep',
    description: 'A beautifully styled snug room honoring York\'s Roman defense walls. Decorated in warm terracotta and stone tones, featuring a plush queen-size Harrison Spinks pocket-sprung bed, soft dimmable accent lighting, and an ensuite shower room.',
    pricePerNight: 145,
    weekendPrice: 170,
    maxGuests: 2,
    bedType: 'Double / Queen Bed',
    sizeSqM: 26,
    floor: '1st Floor',
    view: 'Historic Medieval Alley & City Wall line',
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Harrison Spinks Luxury Bed',
      'Modern Ensuite with Powerful Shower',
      'Yorkshire Welcome Treats',
      'Smart 43" TV with Chromecast',
      'Ultra-Fast Wi-Fi',
      'Eco-friendly Luxury Toiletries',
      'Compact Laptop Workstation',
      'Blackout Window Drapes'
    ],
    highlights: [
      'Exceptional value in central York',
      'Whisper quiet for deep sleep',
      'Steps away from Bootham Bar'
    ],
    badge: 'Best Value',
    totalUnits: 1,
  },
  {
    id: 'jorvik-courtyard-cottage',
    name: 'The Jorvik Courtyard Cottage (Family/Studio)',
    slug: 'jorvik-courtyard-cottage',
    tagline: 'Private ground floor retreat with patio & kitchenette',
    description: 'A self-contained garden suite located in our secluded rear courtyard. Features a master king bedroom, an optional double sofa bed for children or additional guests, a sleek breakfast kitchenette with SMEG kettle and toaster, and direct access to the garden terrace.',
    pricePerNight: 260,
    weekendPrice: 295,
    maxGuests: 4,
    bedType: '1 King Bed + 1 Luxury Double Sofa Bed',
    sizeSqM: 50,
    floor: 'Ground Floor (Direct Access, Step-Free)',
    view: 'Private Courtyard & Herb Garden',
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Direct Private Terrace Access',
      'Step-Free Ground Floor Accessibility',
      'Breakfast Kitchenette (Fridge, Microwave, Sink, SMEG)',
      'Spacious Dining & Lounge Area',
      'Accommodates up to 4 Guests',
      'Large Walk-in Double Shower',
      'Two Smart 50" 4K TVs',
      'Ultra-Fast Wi-Fi',
      'Garden Seating & Outdoor Lanterns'
    ],
    highlights: [
      'Ideal for families or longer stays',
      'Step-free ground level access',
      'Private outdoor garden patio'
    ],
    badge: 'Family & Long Stay',
    totalUnits: 1,
  },
  {
    id: 'cliffords-loft-snug',
    name: 'The Clifford\'s Tower Loft',
    slug: 'cliffords-tower-loft',
    tagline: 'Cozy loft charm with exposed brick & skylight stargazing',
    description: 'A uniquely atmospheric room nestled into the historic eaves with exposed brickwork and Velux roof windows allowing you to stargaze from bed. Features a sumptuous king bed, retro Marshall Bluetooth speaker, and a contemporary slate-tiled bathroom.',
    pricePerNight: 160,
    weekendPrice: 185,
    maxGuests: 2,
    bedType: 'King Size Bed',
    sizeSqM: 30,
    floor: '3rd Floor (Loft)',
    view: 'Skyline & St. Olave\'s Church Spire',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Velux Roof Skylights with Stargazing Blinds',
      'Marshall Bluetooth Sound System',
      'Walk-in Slate Shower',
      'Artisan York Gin Welcome Miniature',
      'Smart 43" 4K TV',
      'Ultra-Fast Wi-Fi',
      'Luxury Bramley Toiletries',
      'Cozy Reading Chair'
    ],
    highlights: [
      'Romantic eaves architecture',
      'Velux stargazing skylights',
      'Complimentary York Gin taster'
    ],
    badge: 'Romantic Loft',
    totalUnits: 1,
  }
];

export const BOOKING_ADD_ONS: BookingAddOn[] = [
  {
    id: 'addon-yorkshire-breakfast',
    name: 'Traditional Yorkshire Farmhouse Breakfast Hamper',
    description: 'Locally sourced dry-cured bacon, Cumberland sausages, free-range Stillington eggs, sourdough bread, Wensleydale butter, and Yorkshire Gold tea delivered freshly to your door.',
    price: 18,
    perPerson: true,
    perNight: true,
    iconName: 'Coffee'
  },
  {
    id: 'addon-parking-permit',
    name: 'Guaranteed Secure Private Parking Space',
    description: 'Reserved off-street bay in our private gated courtyard with 24/7 CCTV and Type 2 EV charging access (rare in central York).',
    price: 15,
    perNight: true,
    iconName: 'Car'
  },
  {
    id: 'addon-ghost-tour',
    name: 'VIP York Ghost & Mystery Walk Pass',
    description: 'Priority guest entry to the famous Original Ghost Walk of York from The King\'s Arms, led by York\'s master storytellers.',
    price: 12,
    perPerson: true,
    iconName: 'Moon'
  },
  {
    id: 'addon-champagne-truffles',
    name: 'Chilled Champagne & York Chocolate Truffles',
    description: 'A bottle of chilled Taittinger Brut Reserve Champagne paired with artisan handmade truffles from York Cocoa Works ready in your room.',
    price: 55,
    iconName: 'Sparkles'
  },
  {
    id: 'addon-late-checkout',
    name: 'Lazy Sunday Late Check-out (1:00 PM)',
    description: 'Enjoy a leisurely morning without rushing. Extends your departure from 11:00 AM to 1:00 PM.',
    price: 25,
    iconName: 'Clock'
  }
];

export const ATTRACTIONS: Attraction[] = [
  {
    id: 'york-minster',
    name: 'York Minster Cathedral',
    category: 'Heritage & Sights',
    distance: '6 min walk (0.3 mi)',
    duration: '2 - 3 hours',
    rating: 4.9,
    reviewCount: 14820,
    address: 'Deangate, York YO1 7HH',
    description: 'One of the world\'s most magnificent cathedrals, showcasing awe-inspiring gothic architecture, medieval stained glass including the Great East Window (the size of a tennis court), and subterranean Roman crypts.',
    insiderTip: 'Book the Tower Climb ticket for sunset! You will climb 275 steps up the Central Tower for the best panoramic 360° viewpoint across North Yorkshire.',
    imageUrl: 'https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Mon-Sat: 09:30 - 16:00, Sun: 12:45 - 15:15',
    priceNote: '£18 adult (ticket valid for 12 months)',
    guestPerk: 'Show your York Guest House keycard for 10% discount at the Minster Gift Shop.',
    mapCoords: { lat: 53.9623, lng: -1.0819 }
  },
  {
    id: 'the-shambles',
    name: 'The Shambles & Medieval Quarter',
    category: 'Heritage & Sights',
    distance: '9 min walk (0.5 mi)',
    duration: '1 - 2 hours',
    rating: 4.8,
    reviewCount: 22100,
    address: 'The Shambles, York YO1 7LZ',
    description: 'Britain\'s most picturesque preserved 14th-century timber-framed street, famous for its overhangs that almost touch overhead. Said to have inspired Diagon Alley in Harry Potter, packed with boutique chocolatiers, potion shops, and bakeries.',
    insiderTip: 'Visit early morning (before 9:00 AM) or after 7:00 PM to photograph the cobbled lanes without crowds and enjoy the enchanting gas lamp glow.',
    imageUrl: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Open 24/7 (Individual shops 10:00 - 17:30)',
    priceNote: 'Free to explore',
    guestPerk: 'Free York Cocoa Works tasting voucher available from our concierge desk.',
    mapCoords: { lat: 53.9596, lng: -1.0799 }
  },
  {
    id: 'jorvik-viking-centre',
    name: 'JORVIK Viking Centre',
    category: 'Family & Culture',
    distance: '11 min walk (0.6 mi)',
    duration: '1.5 hours',
    rating: 4.7,
    reviewCount: 9400,
    address: 'Coppergate, York YO1 9WT',
    description: 'Built directly atop the genuine 10th-century archaeological excavations of Viking York. Ride in state-of-the-art time capsules through reconstructed timber houses, meeting 22 life-like animatronic Norse figures complete with authentic sights, sounds, and smells.',
    insiderTip: 'Pre-booking time slots online is strictly essential during peak weekends. Ask our reception to book your fast-track priority slot.',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Daily: 10:00 - 17:00',
    priceNote: '£16.50 adult / £11.00 child',
    guestPerk: 'Priority reservation window for York Guest House residents.',
    mapCoords: { lat: 53.9577, lng: -1.0805 }
  },
  {
    id: 'bettys-tea-rooms',
    name: 'Bettys Café Tea Rooms',
    category: 'Food & Tea Rooms',
    distance: '7 min walk (0.4 mi)',
    duration: '1 - 1.5 hours',
    rating: 4.8,
    reviewCount: 16500,
    address: '6-8 St. Helen\'s Square, York YO1 8QN',
    description: 'Founded in 1919, Bettys is the quintessential English luxury tea experience. Experience silver cake stands laden with warm scones, Yorkshire clotted cream, delicate finger sandwiches, and live grand piano accompaniment in the Belmont Room.',
    insiderTip: 'The main ground queue can reach 45 minutes at noon. Arrive at 9:00 AM for breakfast rosti or reserve the Belmont Room Afternoon Tea 2 weeks in advance.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Sun-Fri: 09:00 - 17:30, Sat: 08:30 - 18:00',
    priceNote: 'Traditional Afternoon Tea from £42.95',
    guestPerk: 'Complimentary Bettys handmade spiced biscuit tin in your room upon arrival.',
    mapCoords: { lat: 53.9602, lng: -1.0847 }
  },
  {
    id: 'cliffords-tower',
    name: 'Clifford\'s Tower & Castle Museum',
    category: 'Heritage & Sights',
    distance: '14 min walk (0.8 mi)',
    duration: '1 - 2 hours',
    rating: 4.6,
    reviewCount: 8200,
    address: 'Tower St, York YO1 9SA',
    description: 'The monumental stone keep crowning William the Conqueror\'s motte-and-bailey castle. Recently transformed with an architectural timber deck walkway offering spectacular elevated views across the River Ouse and historic skyline.',
    insiderTip: 'Combine with the adjacent York Castle Museum across the lawn to walk through Kirkgate, a fully reconstructed authentic Victorian cobblestone street.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Daily: 10:00 - 17:00',
    priceNote: '£9.50 adult (Free for English Heritage)',
    mapCoords: { lat: 53.9558, lng: -1.0792 }
  },
  {
    id: 'national-railway-museum',
    name: 'National Railway Museum',
    category: 'Family & Culture',
    distance: '15 min walk (0.9 mi)',
    duration: '2.5 - 4 hours',
    rating: 4.9,
    reviewCount: 19800,
    address: 'Leeman Rd, York YO26 4XJ',
    description: 'The world\'s greatest railway museum, home to the record-breaking Mallard steam locomotive, the luxurious Victorian royal carriages of Queen Victoria, and the Japanese Shinkansen bullet train.',
    insiderTip: 'Admission is completely free! Don\'t miss the live locomotive turntable demonstration in the Great Hall at 11:30 and 14:30.',
    imageUrl: 'https://images.unsplash.com/photo-1532105956626-9569c03602f6?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Wed-Sun: 10:00 - 17:00 (Open 7 days during school holidays)',
    priceNote: 'Free Admission (Donations welcomed)',
    mapCoords: { lat: 53.9600, lng: -1.0963 }
  },
  {
    id: 'york-city-walls',
    name: 'York Historic City Walls & Bars',
    category: 'Walks & Scenery',
    distance: '2 min walk from Guest House (0.1 mi)',
    duration: '2 hours full loop (3.4 km)',
    rating: 4.9,
    reviewCount: 11200,
    address: 'Bootham Bar Access, St. Leonard\'s Pl, York',
    description: 'The longest and best-preserved medieval city defense walls in England. A stunning elevated 2-mile circuit providing scenic perspectives over gardens, the Minster, moat ramparts, and four monumental gatehouse bars (Bootham, Micklegate, Monk, Walmgate).',
    insiderTip: 'Start your walk right outside our front door at Bootham Bar. The stretch between Bootham Bar and Monk Bar has the finest direct views of York Minster.',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Open daily from 08:00 until dusk',
    priceNote: 'Free access',
    guestPerk: 'Ask reception for our laminated Pocket Guide to York Walls with secret trivia.',
    mapCoords: { lat: 53.9628, lng: -1.0858 }
  },
  {
    id: 'original-ghost-walk',
    name: 'The Original Ghost Walk of York',
    category: 'Ghost & Mystery',
    distance: '10 min walk (0.5 mi)',
    duration: '1.5 hours',
    rating: 4.8,
    reviewCount: 7600,
    address: 'The King\'s Arms, Ouse Bridge, York YO1 9SN',
    description: 'Believed to be the world\'s very first official ghost walk (established 1973). Walk through shadowy medieval snickelways where Roman legions, plague victims, and highwaymen like Dick Turpin still roam York, Europe\'s most haunted city.',
    insiderTip: 'Departs every night at 7:30 PM sharp from The King\'s Arms pub garden beside the River Ouse. Arrive 15 minutes early for a pint of Yorkshire bitter.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1000&q=80',
    openingHours: 'Every evening at 19:30',
    priceNote: '£9.00 adult / £6.00 child',
    guestPerk: 'Discounted VIP tickets bookable directly in your room reservation.',
    mapCoords: { lat: 53.9571, lng: -1.0838 }
  }
];

export const INITIAL_CHANNEL_SYNCS: ChannelSyncStatus[] = [
  {
    id: 'sync-airbnb',
    name: 'Airbnb Instant Sync',
    platform: 'Airbnb',
    status: 'ACTIVE',
    lastSync: '12 seconds ago',
    syncedListingsCount: 6,
    activeReservationsCount: 14,
    rateParity: 100,
    autoSyncIntervalMins: 3,
    icalUrl: 'https://sync.theyorkguesthouse.co.uk/ical/airbnb/feed-993.ics'
  },
  {
    id: 'sync-booking-com',
    name: 'Booking.com XML Two-Way API',
    platform: 'Booking.com',
    status: 'ACTIVE',
    lastSync: '45 seconds ago',
    syncedListingsCount: 6,
    activeReservationsCount: 18,
    rateParity: 100,
    autoSyncIntervalMins: 2,
    icalUrl: 'https://sync.theyorkguesthouse.co.uk/ical/bcom/feed-441.ics'
  },
  {
    id: 'sync-expedia',
    name: 'Expedia Partner Central Connect',
    platform: 'Expedia',
    status: 'ACTIVE',
    lastSync: '1 minute ago',
    syncedListingsCount: 6,
    activeReservationsCount: 8,
    rateParity: 100,
    autoSyncIntervalMins: 5,
    icalUrl: 'https://sync.theyorkguesthouse.co.uk/ical/expedia/feed-208.ics'
  },
  {
    id: 'sync-vrbo',
    name: 'VRBO / HomeAway Fast-Sync',
    platform: 'VRBO',
    status: 'ACTIVE',
    lastSync: '3 minutes ago',
    syncedListingsCount: 4,
    activeReservationsCount: 5,
    rateParity: 100,
    autoSyncIntervalMins: 10,
    icalUrl: 'https://sync.theyorkguesthouse.co.uk/ical/vrbo/feed-112.ics'
  }
];

// Seed initial bookings across direct and OTAs to demonstrate realistic real-time multi-platform inventory & conflict prevention
export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'b-direct-101',
    referenceNumber: 'YRK-8419-01',
    roomId: 'minster-penthouse',
    roomName: 'The Minster View Penthouse',
    guestName: 'Eleanor & James Vance',
    guestEmail: 'eleanor.vance@example.co.uk',
    guestPhone: '+44 7700 900142',
    checkIn: '2026-09-04',
    checkOut: '2026-09-07',
    nights: 3,
    guestsCount: 2,
    baseAmount: 785,
    addOnsAmount: 91,
    vatAmount: 175.20,
    cityLevy: 12.00,
    totalAmount: 1063.20,
    addOns: [
      { id: 'addon-yorkshire-breakfast', name: 'Yorkshire Breakfast Hamper', price: 18, quantity: 2 },
      { id: 'addon-champagne-truffles', name: 'Chilled Champagne & Truffles', price: 55, quantity: 1 }
    ],
    channelSource: 'DIRECT',
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    cardLast4: '4242',
    cardBrand: 'Visa Signature',
    status: 'CONFIRMED',
    createdAt: '2026-08-28T14:22:00Z',
    specialRequests: 'Celebrating 10th wedding anniversary. Would appreciate late afternoon arrival check-in instructions.',
    arrivalTime: '15:30',
    isDoubleBookingProtected: true,
  },
  {
    id: 'b-airbnb-202',
    referenceNumber: 'AB-9831-55',
    roomId: 'shambles-georgian-suite',
    roomName: 'The Shambles Georgian Suite',
    guestName: 'Dr. Michael Chen',
    guestEmail: 'm.chen@hospital.org.uk',
    guestPhone: '+44 7890 123456',
    checkIn: '2026-09-03',
    checkOut: '2026-09-05',
    nights: 2,
    guestsCount: 2,
    baseAmount: 390,
    addOnsAmount: 0,
    vatAmount: 78.00,
    cityLevy: 8.00,
    totalAmount: 476.00,
    addOns: [],
    channelSource: 'AIRBNB',
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    cardLast4: '8810',
    cardBrand: 'Mastercard',
    status: 'CONFIRMED',
    createdAt: '2026-08-30T10:15:00Z',
    specialRequests: 'Attending medical conference at University of York.',
    arrivalTime: '16:00',
    isDoubleBookingProtected: true,
  },
  {
    id: 'b-bcom-303',
    referenceNumber: 'BK-5521-89',
    roomId: 'eboracum-royal-deluxe',
    roomName: 'The Eboracum Royal Deluxe',
    guestName: 'Sophie & Oliver Davies',
    guestEmail: 'sophie.davies@outlook.com',
    guestPhone: '+44 7911 234567',
    checkIn: '2026-09-06',
    checkOut: '2026-09-09',
    nights: 3,
    guestsCount: 2,
    baseAmount: 555,
    addOnsAmount: 45,
    vatAmount: 120.00,
    cityLevy: 12.00,
    totalAmount: 732.00,
    addOns: [
      { id: 'addon-parking-permit', name: 'Guaranteed Secure Parking', price: 15, quantity: 3 }
    ],
    channelSource: 'BOOKING_COM',
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    cardLast4: '3192',
    cardBrand: 'Amex',
    status: 'CONFIRMED',
    createdAt: '2026-08-31T09:40:00Z',
    specialRequests: 'Arriving by electric vehicle; EV charger bay required.',
    arrivalTime: '14:30',
    isDoubleBookingProtected: true,
  },
  {
    id: 'b-vrbo-404',
    referenceNumber: 'VR-1120-74',
    roomId: 'jorvik-courtyard-cottage',
    roomName: 'The Jorvik Courtyard Cottage (Family/Studio)',
    guestName: 'The Harrison Family (4 guests)',
    guestEmail: 'rachel.harrison@btinternet.com',
    guestPhone: '+44 7722 889900',
    checkIn: '2026-09-08',
    checkOut: '2026-09-12',
    nights: 4,
    guestsCount: 4,
    baseAmount: 1040,
    addOnsAmount: 60,
    vatAmount: 220.00,
    cityLevy: 16.00,
    totalAmount: 1336.00,
    addOns: [
      { id: 'addon-parking-permit', name: 'Guaranteed Secure Parking', price: 15, quantity: 4 }
    ],
    channelSource: 'VRBO',
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    cardLast4: '9012',
    cardBrand: 'Visa',
    status: 'CONFIRMED',
    createdAt: '2026-08-25T11:00:00Z',
    specialRequests: 'Travelling with two children (aged 8 & 11) for Viking festival.',
    arrivalTime: '15:00',
    isDoubleBookingProtected: true,
  }
];
